<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Ci\Module'                        => __DIR__ . '/Module.php',
    'Ci\Controller\CiController' => __DIR__ . '/src/Ci/Controller/CiController.php',
    'CiTest\Framework\TestCase'        => __DIR__ . '/tests/Ci/Framework/TestCase.php',
    'CiTest\SampleTest'                => __DIR__ . '/tests/Ci/SampleTest.php',
);
