<?php echo $this->t; ?>
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script>
$.noConflict();
</script>
<div id="bread-wrp">
	<div id="bread">
		<ul>
			<li>Continuous Integration Projects</li>
		</ul>
	</div>
</div>
<script type="text/javascript">
function addNewJobForm() {
	window.location = "/ZendServer/Ci/project";
}

function disableJob() {
	jQuery('#jobs-table tr').each(function(){
		if (jQuery(this).find('input:checkbox').is(':checked')) {
			var jobId = jQuery(this).attr('id');
			jobId = jobId.substring(3);
			var params = 'job-id=' + jobId;
			jQuery.ajax({
				type: "POST",
				url: "/ZendServer/Ci/disable",
				data: params
			})
			.done(function(msg) {
				
			});
			jQuery(this).find('input:checkbox').parent().next().next().next().next().next().html('Disabled');		
		}
	});
}

function enableJob() {
	jQuery('#jobs-table tr').each(function(){
		if (jQuery(this).find('input:checkbox').is(':checked')) {
			var jobId = jQuery(this).attr('id');
			jobId = jobId.substring(3);
			var params = 'job-id=' + jobId;
			jQuery.ajax({
				type: "POST",
				url: "/ZendServer/Ci/enable",
				data: params
			})
			.done(function(msg) {
				
			});	
			jQuery(this).find('input:checkbox').parent().next().next().next().next().next().html('Enabled');
		}
	});
}

function deleteJob() {
	jQuery('#jobs-table tr').each(function(){
		if (jQuery(this).find('input:checkbox').is(':checked')) {
			var jobId = jQuery(this).attr('id');
			jobId = jobId.substring(3);
			var params = 'job-id=' + jobId;
			jQuery.ajax({
				type: "POST",
				url: "/ZendServer/Ci/delete",
				data: params
			})
			.done(function(msg) {
				
			});
			jQuery(this).find('input:checkbox').parent().parent().remove();		
		}
	});
}

function selectJob(jobId) {
	window.location = "/ZendServer/Ci/project?jobId=" + jobId;
}

function forceRun(ruleId) {
    var request = new Request.WebAPI({
        url: '/ZendServer/Api/jobqueueRunNowRule',
        data: {ruleId: ruleId}, 
        onSuccess: function(response) {
            document.fireEvent('toastNotification', {'message': 'The recurring job was scheduled for immediate execution'});
			//console.log(response);
			window.location = '/ZendServer/JobQueue/';
        },
        onFailure: function(response) {
            document.fireEvent('toastAlert', {'message': 'Failed to execute the recurring job'});
        }
    }).post();
}

function addNewProjectFromTemplate() {
	window.location = "/ZendServer/Ci/projectFromTemplate";
}
</script>
<style>
.tbl-border table, th, td {
	border: 1px solid #DDDDDD;
}
</style>
<div class="grid-action-bar" id="grid-action-bar">
	<button onclick="addNewJobForm();">Create New Freestyle CI Project</button>
	<button onclick="addNewProjectFromTemplate();">Create New CI Project from Template</button>
	<button onClick="window.location='/ZendServer/RecurringJobs';">Job Rules</button>
	<button onclick="disableJob();">Disable</button>
	<button onclick="enableJob();">Enable</button>
	<button onclick="deleteJob();">Delete</button>
</div>
<div>
	<table class="zgrid tbl-border" id="jobs-table">
		<thead>
			<tr>
				<th style="width: 30px;">
				
				</th>
				<th>
					Project ID
				</th>
				<th>
					Project Name
				</th>
				<th>
					Project Description
				</th>
				<th>
					Last Build Status	
				</th>
				<th>
				
				</th>
			</tr>
		</thead>
		<tbody>
			<?php
			$success = 0;
			$fail = 0;
			foreach ($this->results as $row) {
				?>
				<tr id="row<?php echo $row['jobid']; ?>">
					<td><input id="cb<?php echo $row['jobid']; ?>" type="checkbox"></td>
					<td><?php echo $row['jobid']; ?></td>
					<td><a href="javascript:void(0);" onClick="selectJob(<?php echo $row['jobid']; ?>);"><?php echo $row['jobname']; ?></a></td>
					<td><?php echo $row['jobdesc']; ?></td>
					<td>
						<?php
						if ($row['lastbuildstatus'] == 'FAILED') {
							$fail++;
							?>
							<span style="color: red;"><?php echo $row['lastbuildstatus']; ?></span>
							<?php
						} else {
							$success++;
							?>
							<span style="color: blue;"><?php echo $row['lastbuildstatus']; ?></span>	
							<?php
						}
						?>
					</td>
					<td>
						<?php 
						if($row['enabled'] == '1') {
							echo "Enabled";
						} else {
							echo "Disabled";
						};
						?>
					</td>
				</tr>
				<?php
			}
			?>
		</tbody>
	</table>
</div>
<div style="text-align: center;">
	<script src="/ZendServer/js/chartjs/Chart.js"></script>
	<div style="text-align: center; padding-top: 10px; display: inline-block;">
		<canvas id="myChart2" width="800" height="400"></canvas>
	</div>
	<br>
	<div style="text-align: center; padding-top: 10px; display: inline-block;">
		<canvas id="myChart" width="400" height="400"></canvas>
	</div>
	<script type="text/javascript">
	var ctx = document.getElementById("myChart").getContext("2d");
	var data = [
		{
			value: <?php echo $success; ?>,
			color:"blue",
			highlight: "blue",
			label: "Success"
		},
		{
			value: <?php echo $fail; ?>,
			color: "red",
			highlight: "red",
			label: "Fail"
		}
	]

	var options = {
		//Boolean - Whether we should show a stroke on each segment
		segmentShowStroke : true,

		//String - The colour of each segment stroke
		segmentStrokeColor : "#fff",

		//Number - The width of each segment stroke
		segmentStrokeWidth : 2,

		//Number - The percentage of the chart that we cut out of the middle
		percentageInnerCutout : 0, // This is 0 for Pie charts

		//Number - Amount of animation steps
		animationSteps : 100,

		//String - Animation easing effect
		animationEasing : "easeOutBounce",

		//Boolean - Whether we animate the rotation of the Doughnut
		animateRotate : true,

		//Boolean - Whether we animate scaling the Doughnut from the centre
		animateScale : false,

		//String - A legend template
		legendTemplate : "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<segments.length; i++){%><li><span style=\"background-color:<%=segments[i].fillColor%>\"></span><%if(segments[i].label){%><%=segments[i].label%><%}%></li><%}%></ul>"

	}
	var myPieChart = new Chart(ctx).Pie(data,options);
	</script>
	<script type="text/javascript">
	var ctx2 = document.getElementById("myChart2").getContext("2d");
	var data2 = {
		<?php
		$str = '';
		foreach ($this->buildStats as $build) {
			$str .= '"' . $build['buildDate'] . ' ' . $build['jobName'] . '", ';
		}
		?>
		labels: [<?php echo $str; ?>],
		datasets: [
			{
				label: "My First dataset",
				fillColor: "rgba(220,220,220,0.5)",
				strokeColor: "rgba(220,220,220,0.8)",
				highlightFill: "rgba(220,220,220,0.75)",
				highlightStroke: "rgba(220,220,220,1)",
				<?php
				$str = '';
				foreach ($this->buildStats as $build) {
					$str .= '"' . $build['buildTime'] . '", ';
				}
				?>
				data: [<?php echo $str; ?>]
			},
		]
	};
	
	var options2 = {
	//Boolean - Whether the scale should start at zero, or an order of magnitude down from the lowest value
	scaleBeginAtZero : true,

	//Boolean - Whether grid lines are shown across the chart
	scaleShowGridLines : true,

	//String - Colour of the grid lines
	scaleGridLineColor : "rgba(0,0,0,.05)",

	//Number - Width of the grid lines
	scaleGridLineWidth : 1,

	//Boolean - If there is a stroke on each bar
	barShowStroke : true,

	//Number - Pixel width of the bar stroke
	barStrokeWidth : 2,

	//Number - Spacing between each of the X value sets
	barValueSpacing : 5,

	//Number - Spacing between data sets within X values
	barDatasetSpacing : 1,
	showScale: false,
	//String - A legend template
	legendTemplate : "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].lineColor%>\"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>"
	
	}
	var myBarChart = new Chart(ctx2).Bar(data2, options2);
	</script>

</div>