<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script>
$.noConflict();
</script>
<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
<script type="text/javascript">
jQuery(document).ready(function(){
		jQuery("#feeder").html('Loading...');
		setInterval(function() {
				jQuery.ajax({url:"/ZendServer/Ci/monitor-ajax",success:function(result){
						$("#feeder").html(result);
				}});
		}, 1000);
});
</script>
<div id="feeder"></div>